version: '3'
services: 
  api: 
    build: 
      context: ./backend
    container_name: api
    ports: 
      - "3000:3000"
  ui: 
    build: 
      context: ./frontend
    container_name: ui
    ports: 
      - "4200:4200"
    stdin_open: true
  nginx: 
    container_name: nginx
    depends_on: 
      - ui
      - api
    ports: 
      - "80:80"
    build:
      context: ./nginx